### ISSUE TITLE
dynamic messages using templates

### ISSUE THREAD

**Issue by X-GeneIT** [hi1280/ngx-validation-messages#4]
How do I show dynamic messages using templates?
e.g. `<p class="caption status-danger"
                *ngIf="showCustomError"> {{ label }} : {{dymamic message goes here}}</p>`

**Comment by hi1280** [comment]
Below is an example to use this module.

1. configure NgxValidationMessagesModule
https://github.com/hi1280/ngx-validation-messages/blob/master/src/app/app.module.ts

2. use NgxValidationMessagesService
https://github.com/hi1280/ngx-validation-messages/blob/master/src/app/template-driven-forms/template-driven-forms.component.ts

3. show messages using a template
https://github.com/hi1280/ngx-validation-messages/blob/master/src/app/template-driven-forms/template-driven-forms.component.html

**Comment by X-GeneIT** [comment]
I checked those links already but I couldn't figure it out. This is where I'm stuck.

**Template:**

`import { Component, Input, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
    selector: 'ngx-validation-message',
    styleUrls: ['./validation-message.component.scss'],
    template: `
             <p class="caption status-danger" *ngIf="showCustomError"> {{ label }} : {{customError}}</p>
  `,
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => NgxValidationMessageComponent),
            multi: true,
        },
    ],
})
export class NgxValidationMessageComponent {
    @Input()
    label: string = '';

    @Input()
    showCustomError?: boolean;

    @Input()
    customError?: string;
}
`
**View:**

`                              <div class="form-group">
                                  <input type="text" nbInput fullWidth shape="semi-round" formControlName="CompanyTypeName"
                                  [status]="CompanyTypeName.dirty ? (CompanyTypeName.invalid  ? 'danger' : 'success') : ''"
                                  [attr.aria-invalid]="CompanyTypeName.invalid && CompanyTypeName.touched ? true : null"
                                  placeholder="Enter Company Type" uppercase>
                                  <ngx-validation-message label="Company Type Name" for = "CompanyTypeName" 
                                  [showRequired]="CompanyTypeName?.errors?.required && CompanyTypeName.touched" 
                                  [showCustomError]="CompanyTypeName?.hasError('customError')">
                                </ngx-validation-message>
                              </div>  `

**Component:**

`this.frmCompanyType.controls["CompanyTypeName"].setErrors({ 'customError' : "some error");`


**Expected result:** Company Type Name : some error.
**Actual result:** Company Type Name :

How do I pass a dynamic message to the template?

**Comment by hi1280** [comment]
I think I need to pass the error message to the `customError` property.
```html
<ngx-validation-message label="Company Type Name" for = "CompanyTypeName" [showRequired]="CompanyTypeName?.errors?.required && CompanyTypeName.touched" [showCustomError]="CompanyTypeName?.hasError('customError')" [customError]="CompanyTypeName?.getError('customError')"> </ngx-validation-message>
```
It does not confirm whether to work.

**Comment by X-GeneIT** [comment]
It worked, thank you and much appreciated!
